# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
def share_pods
 pod 'React', :path => '../node_modules/react-native'
 pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
end

target 'travel_social_network' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  share_pods
  # Pods for travel_social_network

  target 'travel_social_network-tvOSTests' do
    share_pods
    inherit! :search_paths
    # Pods for testing

    pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  end

  target 'travel_social_networkTests' do
    share_pods
    inherit! :search_paths
    # Pods for testing
  end

end


